version: "3"

services:
  db:
    image: mysql:latest
    networks:
      - db-domain
    container_name: db
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: task_manager
      MYSQL_PASSWORD: "1234567890"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes: 
      - ./dump:/docker-entrypoint-initdb.d
    security_opt:
    - seccomp:unconfined
  admin:
    image: phpmyadmin/phpmyadmin
    container_name: php-admin
    ports:
      - "8000:80"
    networks:
      - db-domain
    environment: 
      PMA_HOST: db
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: php-app
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html/
    links:
      - db
    networks: 
      - db-domain

networks:
    db-domain:
